server:
  port: 8888
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/blog?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: "010629"

  data:
    redis:
      host: localhost
      port: 6379
      database: 1
      lettuce:
        pool:
          max-idle: 100
          max-active: 100
          max-wait: 10000
          min-idle: 10
  mail:
    host: smtp.qq.com
    username: 2783123570@qq.com
    password: gysosamophfkdegg
    default-encoding: UTF-8
    protocol: smtp
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          ssl:
            enable: true
          starttls:
            enable: true
            required: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 3000
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.example.framework
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

upload:
  mode: local
  minio:
    url: http://localhost:9090/blog/
    endpoint: http://localhost:9090
    accesskey: minioadmin
    secretKey: minioadmin
    bucketName: blog
  local: /blog/images
website:
  url: http://localhost:8888